name: Verify

on: [pull_request]

jobs:
    verify:
        runs-on: ubuntu-latest
        name: Verify
        steps:
            - uses: actions/checkout@v2
            - name: Check formatting
              uses: lgeiger/black-action@
              with:
                  args: 'generate.py --check'
            - name: Install python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
                  architecture: 'x64'
            - name: Install pip
              run: python -m pip install --upgrade pip
            - name: Install deps
              run: pip install -r requirements.txt
            - name: Generate site
              run: python generate.py
